---
# I have no idea how it is implemented, but it reduces playbook runtime by factor of three!
ansible_ssh_pipelining: true

# default: login as user & get sudo
ansible_become: true

apt_cache_valid_time: 28800 # 8h

# link vault to plaintext
root_password_digest: '{{ vault_root_password_digest }}'
root_password_mtime: '{{ vault_root_password_mtime }}'
ansible_slack_token: '{{ vault_ansible_slack_token }}'

# One can generate SSHA with ../scripts/ngx-mkpasswd
prometheus_scraper_ssha: '{{ vault_prometheus_scraper_ssha }}' # xref: prometheus_scraper_password

ansible_python_interpreter: /usr/bin/python3

passwd:
  # services
  # - uid [2000, 10000), grouped together by "service"
  # - base for next service is `echo $(( 2000 + 50*($RANDOM % 160) ))`
  # - login name must be <= 8 chars to be nice to `top` util
  nodeexp:  {login: nodeexp, comment: Prometheus Node Exporter} # DONE
  prometh:  {login: prometh, comment: Prometheus Poller}
  alertman: {login: alertman, comment: Prometheus Alert Manager}
  prombbox: {login: prombbox, comment: Prometheus Blackbox Exporter}
  grafana:  {login: grafana, comment: Grafana for Prometheus}
  ngxprom:  {login: ngxprom, comment: nginx for Prometheus exporters} # DONE
  pushgw:   {login: pushgw, comment: Prometheus Pushgateway}

  piwik:    {login: piwik, comment: Piwik user}

  prtreg:   {login: prtreg, comment: Orchestration Registry}
  prtevent: {login: prtevent, comment: Orchestration Events}
  prtnotif: {login: prtnotif, comment: Orchestration Notifications}
  prtfront: {login: prtfront, comment: Orchestration Front}

  explorer: {login: explorer, comment: OONI Explorer}

  oomsmweb: {login: oomsmweb, comment: OONI Measurements WebAPI}

  anaconda: {login: anaconda, comment: Anaconda python user}
  jupyter: {login: jupyter, comment: Jupyter python user}

  ooni_run: {login: oonirun, comment: OONI Run user}

  bouncer: {login: bouncer, comment: OONI Bouncer user}
  collector: {login: collector, comment: OONI Collector user}
  sync_user: {login: sync-user, comment: OONI Collector Sync user}
  sshfeeder: {login: sshfeeder, comment: OONI Collector SSH feeder user}

  agrabeli:
    login: agrabeli
    comment: Maria Xynou
    keys: ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDD0JSwM+t3Uz9lS3Mjoz9oo4vOToWyzboZhYQbP8JY5HvFtAvWanWHnUBO91t6hkgKIMiUqhdCJn26fqkhSGe/bRBaFUocOmuyfcmZoRdi0qzAskmycJsj/w6vWR4x6MYkmJvSeI/MGxjEFt4s2MfOG1tP8CBLUYft9qUleeJa7Jln8c+xbnqB7YngaI190icQHE9NuIB2CXvzbmo3tLtHNMagEwI7VoBDj6mxzTxBd9JhuhF4w5uGxxm0Gp1hzk+15obNnaBS+Anr7jXz8FPwwxCH+XhBZxB1PPpcIayKrf9iLyGtwmhkdDoWCqYAr1mue3LxFso+TZF4bwE4Cjt1 agrabelh@agrabelh"]
  art:
    login: art
    comment: Arturo Filasto
    keys: ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9her6lZIfP/ulXleu00u3ukdcVEDslkfXzi65JFRXRkKYsdMw7zLvrkvFryqDGsRQwpZo0rlk5o26QNSUR/g2Kf3wEHxxmMcN4+g+f0/fJDKLHSFdL5Z5ACyp5YvjA88vG753qVn7lBINuvCb4wk1sUOWM1WVG5WiszLiJCddYUrgCZWzD3FHyApJ/GGH2A5vTTN8mcQapQaJ9/sgxDw5WT+yMtZ8TW4462x+TaWWGE0WnAd/l6HOFaS14mql0K+MbtRp9EKN2O6+sA0OsjknYpt21ovtEWfBiojjh+4Iz6bTk+M5+fWHwQaxqEcaok22l35GudlmaoTB0OesB/1z art@eclipsis"]
  sbs:
    login: sbs
    comment: Simone Basso
    keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCsifxweF7RnZaI55tLEuW2V9SOA6ZJXizXWp69hs1Vy1zeCkyMHMjtUHVjtiV6m1OStb78iNnXh5KjqaNZy7Ign2HILvtFysWktasgM/Vn04FXN9mkh29fKVqVu5XZpzNoBupjCrc9asJUf/6gCAFQHoQyCNO58/R12iUZBtF9cSaZoX4BfwnCNH66uXQ1EK+D0d2uTqtBrPHdm5rexII7uGvG3+dm/YvPmlj87qW6gJstcRVzAPtjBtf8sQGZBnhV1mGAAHQ168DwiZ1LJwtEAEW2HOhtVDemZNKV/KnDGZOWzF/Ybl+4lIdDHcdk/gpjARJtf92XRTD7FmobduwKVmvXR7hHY8nklWHF+PhQtAqg31y1QhW/g4U/JAd8BhziNE9KF6GZ/CIcDFKLZzpyeB4dg2hnJ6e1RoZvC9ObgVOp0jRMgv0c3GpCwoh2eml01zoxDicPMGzbEnuTduVhW5ebMh23NoYhaMnzDcZaRfT//1OB1vi52dXHj4BCE+4s07DzbR7JLvYwYCtMghAqSkotTDoyjYWF8ymwC6Zg54OSYkyNsjOAgQg1u06+dxNubSB9ZI6woUqY0Fhay/ZkS0sO+skEekE1dZes9NWW/1QVWGOgO8g3aO59+Y6e1YbyJhBG2N05tLn1upuqdEHjdkDX9hYm267oBaAdMMl0+Q== sbasso@dunkerque.local"
  federico:
    login: federico
    comment: Federico Ceratto
    keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDm9vQEIYOOGI5m4sx7M0vrSBX/dyw64gCLxGchlaDJXn1Pj3lAvDNdJIjNl4XLQIm/E0inwo+4orw8a+WY5R+bOD8/86VnvsH8CvqoJDNx6NaIPwVNGjZHGmJ6GZKzSWWpq2Kzcr5LhEmPx+w46M1WHinoUtigEUdrwpPKg9/xTYTQjE61Zu+QK52nhyUOPWpUW5m3444FWlNmrJFnMk2zo/XVA5b4fwpU5UnzQPLTky56Rtn4JJpyeiJHr1IS0B3eQphZ9E/7M3sEJc7KE4I4ULbUEiDjS50eNnwwSfzFNvdSIXgH/YAp8AgMj1TF8lFaxL5eV2UhksfKHGnFVRsl"
  majakomel:
    login: majakomel
    comment: Maja Komel
    keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7gWQL4h/IyMbwDuMIXbTVmNEm8Yx19Ftt0P2e3OyWctSMH7WGaHc6b0dGoGh6Y4x0Kpw5h0iHWshP8Rg0pckNG9LeDjLY9nLR3Jv66ogFQtFi1DAlg4CXe369N70rBN9iurndgXjShW9OV+bY+MOlW8Fmmm67Vg0xFiYuYzjgUOpl4ofkbLGAQ7sJRBzpDV6TqHhGfOdYMDJyfFvurVz0oSyEZPFFRv4Css9iVk7BGsBukCCpUuax8akEeEjxWWCvjYXva7OA0jHKayfPAroZx/OJh01rhFe7wxlu5JwUKOcevvAZqeHh6200C82ijZOCN+Qq9yvxOH+OgzhnQwnoetIbGFgnb4CkDxo7dVLc/DFyObznC4f26f5D1OyPMUX8AEarEVdEPwsEfD2ePQr6qek0XWCWtYvGklb+GRLk9Yn0VL1qwvgrtstHdeXsKONTPKRxaCjWHu18dQaG2qOUnZ+St6SHeL49CN9aav2azNI/YKoQ9SGR4D23XeBRsW8="

# Variables from different places have different precedence, beware of that while overriding group_vars/all variables!
# See https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
adm_logins: [ art, federico, sbs, majakomel ]
shell_logins: [ agrabeli ]
svc_ssh_logins: [ ]
sshd_allow_users: '{{ adm_logins | union(shell_logins) | union(svc_ssh_logins) }}'
root_ssh_authrorized_keys: [ ] # unstructured legacy keys

# to avoid useless `pip` modules in global environment if ansible modules require it
ansible_venv: /root/venv
docker_apt_ver: ""

# that's common for roles nginx-prometheus, fw and various exporters
node_exporter_ipv4: "127.139.92.143" # this addr is not 127.0.0.1 to avoid confusion as external/9100 is SSL and lo/9100 is not
ngxprom_exporter_ports: { 9100: '{{ node_exporter_ipv4 }}' }

ntp_pool: debian
have_ssd: false
...
