---
- import_playbook: ansible-version.yml

- hosts: ams-pg.ooni.org
  roles:
    - role: base-buster
    - role: nftables
    - role: nginx-buster
      tags: nginx
    - role: letsencrypt
      tags: letsencrypt
      expand: yes
      letsencrypt_domains:
        - "ams-pg.ooni.org"
        - "api.ooni.io"
        - "collector.ooni.io"
        - "a.collector.ooni.io"
        - "b.collector.ooni.io"
        - "c.collector.ooni.io"
        - "ps.ooni.io"
        - "ps1.ooni.io"
        - "ps2.ooni.io"
        - "ps3.ooni.io"
        - "ps4.ooni.io"
    - role: ooni-backend
      ssl_domain: ams-pg.ooni.org

- hosts: ams-pg-test.ooni.org
  roles:
    - role: base-bullseye
    - role: nftables
    - role: nginx-buster
      tags: nginx
    - role: dehydrated
      tags: dehydrated
      expand: yes
      ssl_domains:
        # with dehydrated the first entry is the cert FQDN
        # and the other ones are alternative names
        - "ams-pg-test.ooni.org"
    - role: ooni-backend
      ssl_domain: ams-pg-test.ooni.org

- hosts: backend-fsn.ooni.org
  roles:
    - role: base-bullseye
    - role: nftables
    - role: nginx-buster
      tags: nginx
    - role: dehydrated
      tags: dehydrated
      expand: yes
      ssl_domains:
        # with dehydrated the first entry is the cert FQDN
        # and the other ones are alternative names
        - "backend-fsn.ooni.org"
        - "api.ooni.io"
        - "collector.ooni.io"
        - "a.collector.ooni.io"
        - "b.collector.ooni.io"
        - "c.collector.ooni.io"
        - "ps.ooni.io"
        - "ps1.ooni.io"
        - "ps2.ooni.io"
        - "ps3.ooni.io"
        - "ps4.ooni.io"
    - role: ooni-backend
      ssl_domain: backend-fsn.ooni.org
